# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	anyhow@1.0.75
	atomig@0.4.0
	atomig-macro@0.3.0
	bitflags@2.4.1
	camino@1.1.6
	cargo-platform@0.1.4
	cargo_metadata@0.18.1
	cfg-if@1.0.0
	const_format@0.2.32
	const_format_proc_macros@0.2.32
	ctrlc@3.4.1
	diff@0.1.13
	either@1.9.0
	equivalent@1.0.1
	hashbrown@0.14.2
	indexmap@2.0.2
	itertools@0.12.0
	itoa@1.0.9
	libc@0.2.149
	memchr@2.6.4
	nix@0.27.1
	pretty_assertions@1.4.0
	proc-macro2@1.0.69
	quote@1.0.33
	ryu@1.0.15
	semver@1.0.20
	serde@1.0.190
	serde_derive@1.0.190
	serde_json@1.0.107
	serde_spanned@0.6.4
	syn@1.0.109
	syn@2.0.38
	thiserror@1.0.50
	thiserror-impl@1.0.50
	toml@0.8.6
	toml_datetime@0.6.5
	toml_edit@0.20.7
	unicode-ident@1.0.12
	unicode-xid@0.2.4
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
	winnow@0.5.17
	yansi@0.5.1
"

DESCRIPTION="Cargo with less noise: warnings are skipped until errors are fixed, Neovim integration, etc."
HOMEPAGE="https://github.com/alopatindev/cargo-limit"
RESTRICT="mirror"

#SRC_URI="$(cargo_crate_uris ${CRATES})"
SRC_URI="${CARGO_CRATE_URIS}" # TODO
if [[ ${PV} == *9999* ]] ; then
	SCM="git-r3"
	##EGIT_MIN_CLONE_TYPE="single" # TODO
	EGIT_REPO_URI="${HOMEPAGE}"

#	#EGIT_BRANCH="precise-jumps" # TODO
#	EGIT_OVERRIDE_REPO_ALOPATINDEV_CARGO_LIMIT="${HOMEPAGE}"
#	EGIT_OVERRIDE_BRANCH_ALOPATINDEV_CARGO_LIMIT="precise-jumps"
else
	SRC_URI="
		${HOMEPAGE}/archive/${PV}.tar.gz -> ${P}.tar.gz
		${SRC_URI}
	"
fi

inherit cargo "${SCM}"

LICENSE="
	|| ( Apache-2.0 MIT )
	Apache-2.0 MIT
"
SLOT="0"
KEYWORDS="~amd64 ~arm64 ~x86"
IUSE="+nvim"

DEPEND=""
RDEPEND="
	${DEPEND}
	nvim? ( >=app-editors/neovim-0.7.0 )
"
#BDEPEND=""

QA_FLAGS_IGNORED="usr/bin/cargo-l.*"

#QA_FLAGS_IGNORED="usr/bin/cargo-llbench
#	usr/bin/cargo-llbuild
#	usr/bin/cargo-llrun
#	usr/bin/cargo-lltest
#	usr/bin/cargo-llclippy
#	usr/bin/cargo-llcheck
#	usr/bin/cargo-llfix
#	usr/bin/cargo-lbench
#	usr/bin/cargo-lbuild
#	usr/bin/cargo-lrun
#	usr/bin/cargo-ltest
#	usr/bin/cargo-lclippy
#	usr/bin/cargo-lcheck
#	usr/bin/cargo-lfix
#"

src_configure() {
	cargo_src_configure
}

src_compile() {
	#cd cargo-limit || die # TODO
	cargo_gen_config
	cargo_src_compile
}

src_install() {
	if use nvim; then
		QA_FLAGS_IGNORED+="usr/bin/_cargo-limit-open-in-nvim"
	fi
	cargo_src_install
	dodoc README.md # TODO
	#local DOCS=( cargo-limit/README.md )
	#einstalldocs
}
